"""User1

Revision ID: 0ce36d3080c1
Revises: cec23231bf1f
Create Date: 2019-03-25 17:54:29.041166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce36d3080c1'
down_revision = 'cec23231bf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carpark',
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('park_id')
    )
    op.create_index(op.f('ix_Carpark_p_name'), 'Carpark', ['p_name'], unique=True)
    op.create_table('user1',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user1_email'), 'user1', ['email'], unique=True)
    op.create_index(op.f('ix_user1_username'), 'user1', ['username'], unique=True)
    op.drop_index('ix_user1_email', table_name='User1')
    op.drop_index('ix_user1_username', table_name='User1')
    op.drop_table('User1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User1',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user2_pkey')
    )
    op.create_index('ix_user1_username', 'User1', ['username'], unique=True)
    op.create_index('ix_user1_email', 'User1', ['email'], unique=True)
    op.drop_index(op.f('ix_user1_username'), table_name='user1')
    op.drop_index(op.f('ix_user1_email'), table_name='user1')
    op.drop_table('user1')
    op.drop_index(op.f('ix_Carpark_p_name'), table_name='Carpark')
    op.drop_table('Carpark')
    # ### end Alembic commands ###
