"""Carpark

Revision ID: c4e8daf99618
Revises: 0ce36d3080c1
Create Date: 2019-03-25 18:01:28.779935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e8daf99618'
down_revision = '0ce36d3080c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carpark', sa.Column('p_close', sa.String(length=36), nullable=True))
    op.add_column('Carpark', sa.Column('p_open', sa.String(length=36), nullable=True))
    op.add_column('Carpark', sa.Column('p_price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Carpark_p_close'), 'Carpark', ['p_close'], unique=False)
    op.create_index(op.f('ix_Carpark_p_open'), 'Carpark', ['p_open'], unique=False)
    op.create_index(op.f('ix_Carpark_p_price'), 'Carpark', ['p_price'], unique=False)
    op.create_index(op.f('ix_user1_email'), 'user1', ['email'], unique=True)
    op.create_index(op.f('ix_user1_username'), 'user1', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user1_username'), table_name='user1')
    op.drop_index(op.f('ix_user1_email'), table_name='user1')
    op.drop_index(op.f('ix_Carpark_p_price'), table_name='Carpark')
    op.drop_index(op.f('ix_Carpark_p_open'), table_name='Carpark')
    op.drop_index(op.f('ix_Carpark_p_close'), table_name='Carpark')
    op.drop_column('Carpark', 'p_price')
    op.drop_column('Carpark', 'p_open')
    op.drop_column('Carpark', 'p_close')
    # ### end Alembic commands ###
