"""empty message

Revision ID: cec23231bf1f
Revises: 
Create Date: 2019-03-25 17:40:12.924922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec23231bf1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parkhouse')
    op.create_index(op.f('ix_user1_email'), 'user1', ['email'], unique=True)
    op.create_index(op.f('ix_user1_username'), 'user1', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user1_username'), table_name='user1')
    op.drop_index(op.f('ix_user1_email'), table_name='user1')
    op.create_table('parkhouse',
    sa.Column('park_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('popen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('park_id', name='parkhouse_pkey')
    )
    # ### end Alembic commands ###
